### ISSUE TITLE
有没有对应的后台服务

### ISSUE THREAD

**Issue by 976977577** [zouzhibin/zb-admin#12]

**Comment by 976977577** [comment]
最好是nodejs版本的

**Comment by nonhana** [comment]
我也想问，拉下来了，但是在仓库里面没看到对应的后端，作者看到之后可以回一下？

**Comment by 976977577** [comment]
没有的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: non_hana ***@***.***&gt;
发送时间: 2023年10月18日 11:24
收件人: zouzhibin/vue-admin-perfect ***@***.***&gt;
抄送: Tenero ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [zouzhibin/vue-admin-perfect] 有没有对应的后台服务 (Issue #12)





 
我也想问，拉下来了，但是在仓库里面没看到对应的后端，作者看到之后可以回一下？

**Comment by nonhana** [comment]
那就得自己纯手搭？

**Comment by 976977577** [comment]
嗯
