### ISSUE TITLE
刚下载的项目，运行npm run build 打包，打包以后无法显示 

### ISSUE THREAD

**Issue by theLastCc** [zouzhibin/zb-admin#9]
/
![WechatIMG120](https://github.com/zouzhibin/vue-admin-perfect/assets/24369247/31f345ba-37cc-48fe-a8da-f9da4cd757d9)

**Comment by zouzhibin** [comment]
这个打包是可以显示的，可能是你配置的路径不对，你访问的预览地址都是我打包之后的地址
